// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwHjTUX4nOqEcXZgfmy0EQv2LCYT4ZSCo',
    appId: '1:1022325094662:android:f0171152900ce705fe8687',
    messagingSenderId: '1022325094662',
    projectId: 'authentication-proj-a6c88',
    storageBucket: 'authentication-proj-a6c88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQP7a1oVJYQsYCvkzeRe7yEikYvBSFmTo',
    appId: '1:1022325094662:ios:c895a25823b05d36fe8687',
    messagingSenderId: '1022325094662',
    projectId: 'authentication-proj-a6c88',
    storageBucket: 'authentication-proj-a6c88.firebasestorage.app',
    androidClientId: '1022325094662-nl5dj84f1bpulfomrmuh6ne22d5ojr2s.apps.googleusercontent.com',
    iosClientId: '1022325094662-q7q56hd6cbjg7rnj8bt4h4hresilli0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationProj',
  );

}